#!/usr/bin/env bash

##
# Inital setup script for fresh boxes
##

function info () {
	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

function user () {
	printf "\r  [ \033[0;33m??\033[0m ] %s " "$1"
}

function success () {
	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

function warn () {
	printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
}

function fail () {
	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
	echo ''
	exit 1
}

function install_xcode() {
    # Code from https://apple.stackexchange.com/questions/107307/how-can-i-install-the-command-line-tools-completely-from-the-command-line/195963#195963
    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
    PROD=$(softwareupdate -l |
      grep "\\*.*Command Line" |
      tail -n 1 | awk -F"*" '{print $2}' |
      sed -e 's/^ *//' |
      tr -d '\n')
    softwareupdate -i "${PROD}" --verbose;
}

: "${dotfiles_directory:="$HOME/.dotfiles"}"
export dotfiles_directory

# Installs xcode command line tools and accepts the license
if [[ "$(uname -s)" == "Darwin" ]]; then
	if xcode-select -p ; then
		success "Xcode: MacOS command-line tools are already installed"
	else
		info "Xcode: MacOS command-line tools were not installed, installing now"
		if install_xcode ; then
			success "Xcode: Successfully installed macOS command-line tools"
		else
			fail "Xcode: Failed to install macOS command-line tools"
		fi
	fi
fi

# Installs the dotfiles
if [[ -d "$dotfiles_directory" ]]; then
	success "Initial Install: Dotfiles are already installed"
else
	info "Initial Install: Dotfiles are not installed, downloading now"
	if git clone https://github.com/JasonYao/dotfiles.git "$dotfiles_directory" &> /dev/null ; then
		success "Initial Install: Dotfiles are now installed, running configuration now"
	else
		fail "Initial Install: Dotfiles failed to download, please check your internet connection"
	fi
fi

# Runs the dotfiles setup
if "$dotfiles_directory"/bin/upgrade ; then
	success "Initial Install: Dotfiles are now fully installed and configured"
else
	fail "Initial Install: Dotfiles failed to be configured, please try again"
fi
