#!/usr/bin/env bash

##
# Configuration for the nano editor
##

nanorc_configs=(
	html css javascript json asm
	c cmake sh nanorc java python
	tex go ruby
)

# Sets the correct syntax highlighting directory
if [[ "$(uname -s)" == "Darwin" ]]; then
	# OSX's nano config location
	config_path="/usr/local/share/nano"
else
	# Linux's nano config location
	config_path="/usr/share/nano"
fi

if [[ -f $HOME/.nanorc ]]; then
	success "Nano: Editor settings have already been set"
else
	info "Nano: Editor settings have not been applied yet, applying now"
	{
		echo "# Nano editor configuration files"
		echo ""
		echo "set const"
		echo "set tabsize 4"
		echo ""
		echo "# Included syntax highlighting:"

		for config in "${nanorc_configs[@]}"; do
			printf "\tinclude %s/%s.nanorc\n" "$config_path" "${config}"
		done
	} >> "$HOME"/.nanorc

	success "Nano: Editor settings are now applied"
fi
