#!/usr/bin/env bash

##
# OSX specific setup
##

number_of_spaces=3
motd_file="/etc/motd"

function check_homebrew_status () {
	info "Homebrew: Checking brew status"
	if [[ $(which brew) == "" ]]; then
		info "Homebrew: Not found, installing now"
		if echo "\r" | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" ; then
			success "Homebrew: Package manager is now successfully installed"
		else
			fail "Homebrew: Package manager failed to install"
		fi
	else
		success "Homebrew: Package manager is already installed"
	fi
}
export -f check_homebrew_status

# Symlinks all files
install_dotfiles

# Sets up message of the day tailing
	if [ -f "$motd_file" ]; then
		success "MotD: Symlink is already installed"
	else
		if sudo ln -s "$HOME"/.motd /etc/motd ; then
			success "MotD: Symlink is now installed"
		else
			fail "MotD: Symlink failed to be created"
		fi
	fi

# Checks for OSX defaults
	if "$dotfiles_directory"/osx/setup-defaults ; then
		success "OSX: Sane defaults installed"
	else
		fail "OSX: Failed to set sane defaults"
	fi

# Homebrew status check
	check_homebrew_status

# GNU Bash 4+ check due to using associative arrays
	if [[ $(which bash) == "/bin/bash" ]]; then
		info "Homebrew: Installing latest bash now"
		if brew install bash ; then
			success "Homebrew: Latest bash is now installed"
		else
			fail "Homebrew: Latest bash failed to be installed"
		fi
	fi

# Homebrew dependency check
	info "Homebrew: Checking dependencies status"
	if "$dotfiles_directory"/osx/homebrew/dependencies ; then
		success "Homebrew: All dependencies are installed"
	else
		fail "Homebrew: Some dependencies failed to be installed"
	fi

# Homebrew cask check
	info "Homebrew Casks: Checking cask applications status"
	if "$dotfiles_directory"/osx/homebrew/casks ; then
		success "Homebrew Casks: All cask applications are installed"
	else
		fail "Homebrew Casks: Some cask applications failed to be installed"
	fi

# Development environment check
	info "Dev Environment: Checking environment status"
	if "$dotfiles_directory"/common/dev-setup; then
		success "Dev Environment: All environments are installed and ready"
	else
		fail "Dev Environment: Failed to install some environments correctly"
	fi

# iTerm environment check
	info "iTerm: Checking terminal status"
	if "$dotfiles_directory"/osx/terminal/setup; then
		success "Terminal: All terminal defaults are set"
	else
		fail "Terminal: Some terminal defaults failed to be set"
	fi

# Sets up background images
	info "Background Image: Checking background image status"
	# Note the enclosing single quotes around bash variables when trying to use them in applescripts
	if osascript -e 'tell application "System Events" to set picture of every desktop to ("'$dotfiles_directory'/img/background1.png" as POSIX file as alias)' ; then
		success "Background: Desktop image is now correctly set"
	else
		fail "Background: Desktop image failed to be set"
	fi
