#!/usr/bin/env bash

##
# Installs cask applications
##

cask_packages=(
	google-chrome atom qbittorrent skype synergy filezilla
	flux vlc mactex texmaker torguard jetbrains-toolbox smcfancontrol
	little-snitch micro-snitch
)

function check_homebrew_cask_package() {
	if [[ $(brew cask list | grep "$1") == "" ]]; then
		info "Homebrew-Cask: Package $1 has not been installed yet, installing now"
		brew tap homebrew/dupes
		if brew cask install "$1" &> /dev/null ; then
			success "Homebrew Casks: Package $1 is now installed"
		else
			fail "Homebrew Casks: Package $1 failed to install"
		fi
	else
		success "Homebrew Casks: Package $1 is already installed"
	fi
}

# Updates and upgrades brew packages
	info "Homebrew Casks: Updating brews now"
	if brew cask update; then
		success  "Homebrew Casks: Brews have been updated"
	else
		fail "Homebrew Casks: Brews failed to be updated"
	fi

# Checks and installs any missing packages
	info "Homebrew Casks: Checking installed packages"
	for package in "${cask_packages[@]}"; do
		check_homebrew_cask_package "${package}"
	done
